= All India Convention for Students' Struggles
// See https://hubpress.gitbooks.io/hubpress-knowledgebase/content/ for information about the parameters.
http://i.imgur.com/h6I0mzf.jpg
// :published_at: 2017-08-10
// :hp-tags: Students, Struggle, Bangalore, Declaration
// :hp-alt-title: AICSS

The Students' Outpost would like to declare its solidarity with the students and organizations of the All India Convention for Students' Struggles. Sunday’s Convention brought together hundreds of progressive students and allies to present a collective challenge to the systematic assault on higher education in India. TSO's participation at the convention has given us immense hope and valuable insights on how to take the fight forward. In the coming months, we shall be formalizing a structure and gradually expanding operations. The National Council will also accommodate a TSO representative who will coordinate with various people's movements on the council as we begin our journey to reclaim political space for students in the city.

*BANGALORE DECLARATION*

The formal adoption of the neoliberal reforms programme by the Government of India (GOI) in 1991 had a far more pervasive impact on the education system and policy than is usually recognized. The commercialization and marketization of education put it outside the grasp of the majority of India’s population, 78% of whom by GOI’s own reckoning, were living on less than twenty rupees per day, and altered the concepts of knowledge, education, and its curricular content. 
This outcome is not accidental. It follows from the neoliberal policies of marketization of education as a ‘private good’, and of knowledge as a tradable `commodity’ or `service’, that have been pursued by successive governments for more than three decades. Since the 1970’s `neoliberalism’ has emerged as the `solution’ favoured by international finance capital to cope with recurring economic crises. The “opening up” of the entire range of human activities to penetration by private capital is accomplished through the diversion of public funds and assets into private hands through Public Private Partnerships (PPP). This has a very negative impact on education, health, employment and job security, food security, housing and provision of public utilities, all of which imposes a heavy burden on the most vulnerable sections of society. “Austerity measures” keep production and consumption by the masses under tight control and as a result the erstwhile modern `welfare’ state of the 20th C is transformed. Peoples control over their own lives shrinks as corporations take-over decision-making in the name of “efficiency” and “professional management”.
The uncontrolled privatization and marketization of education has been pursued by all governments, whether led by the UPA, the UF or the NDA, who adhered to this policy despite strong opposition to privatization from students unions and teachers associations who raised issues of the neglect and decline of government schools, colleges and universities, and the protests against fee-hikes largely by urban middle-class parents associations. The exclusion of deprived sections of society due to these policies became increasingly apparent.
However, since the present regime has taken office in 2014, this policy has been combined with the Hindutva ideological and socio-political assault in public life and on the content and syllabi of school and higher education in a form so virulent that it threatens the very conception and purpose of education both for the individual and society. Re-writing history, bolstering and promoting dangerously prejudicial and retrogressive belief systems, reducing learning to the mere acquisition of skills geared to market needs, and maligning intellectual and socio-politically sensitive critical enquiry as “extremist”, “anti-national” and a seditious threat to state security have become today’s common sense and are used as justification for current policy. No free debate or discussion is encouraged or tolerated; governmental dictates are routinely imposed, frequently in violation of established statues and norms of functioning in educational institutions.
The appointment of RSS cadre/ sympathizers in top academic and administrative positions in all institutions and academic bodies has grave implications for the credibility of natural and social sciences research and the future content and quality of investigative studies. The necessary and vibrant exchange of ideas through campus exchanges and interactions, through academic seminars, conferences and publications is being severely restricted by vigilante censorship and policing of all such activities.
The Prime Minister advocates military discipline and commands that all schools should run like Sainik Schools in order to instill nationalism in the students. The Vice-Chancellor of the Jawaharlal Nehru University organizes a demonstration on the campus, complete with retired generals regularly seen in TV studios, to demand that a tank be ceremoniously placed in the university to remind students that the real patriots and their role models must be the armed forces. The 18th C English poet Tennyson had in his poem, “The Charge of the Light Brigade”, written of the prime virtue required of soldiers by ruling elites: “theirs not to question why; theirs but to do and die”. 
One immediately recalls the perceptive insight contained in the Report of the Education Commission (1964-66): ”The character of a university as a society of teachers and students engaged in the pursuit of learning and discovery, distinguishes fundamentally the regulation of its affairs from, say, the profit-motivated management of commercial or industrial concerns or the administration of a government department or municipal corporation, or a unit of the armed forces . . . .Rules, regulations and techniques that hamper the real achievement of the real purposes of the university should be modified or scrapped – they should not be allowed to become a strait-jacket into which all university activities must be fitted.” (p 299)
Today we are seeing the reverse process. The educational calendar, initially in schools but now also in higher education, at the central and state government levels, is becoming more and more bureaucratically controlled by a series of `official’ events, e.g. Swachch Bharat campaign, Yoga Day, Man ki Baat sessions. Policies promoting Sanskrit, through compulsory observance of Sanskrit Week, and `sanskritization’ to venerate Brahmanism, the introduction of compulsory Yoga/ Surya Namaskar etc., in all government schools and even in higher educational institutions (HEIs) receive official sanction and backing. Gazetted holidays for festivals of minority communities are increasingly being turned into official days or commemorative events at schools so that the presence of teachers and students is mandatory. 
Central and state governments, often utilizing the University Grants Commission which has long ceased to function as a buffer between political leaderships, administrative bureaucracies and the academic community, have been taking steps to curb the intellectual and even physical space that is available for students and faculty to question, dissent from and disturb existing power structures. Universities have been issuing circulars that warn students against protests and demand signed bonds at the time of admission stating that they will not protest against the conduct and policies of the authorities. Geographical and intellectual space for dissent is denied by withholding permission for meetings to both faculty and students. Surveillance cameras across campuses pressurize the community to adopt forms of self-disciplining and pre-censorship. On top of all this is the constant threat of unrestrained police entry on campuses. This condemnable treatment of students and faculty as if they are criminals engaged in the now illegitimate activity of dissent when they confront anti-democratic, anti-people actions of the government and educational authorities, needs to be challenged to ensure that dissent of all kinds is freely allowed inside university premises, which not only set up a model for but also interact through public spaces outside educational institutions as well. The critical and analytical voices from the country’s campuses are heard well beyond their boundaries. 
The All India Convention of Students’ Struggle salutes the student community rising up as an irrepressible force against oppressive, discriminatory and socially unjust policies and practices of the state, because they are not only defending their own rights but are also struggling for the rights of the oppressed and all those who bear the brunt of an authoritarian political regime committed to a sharply unequal economic and social agenda. The students are carrying forward a treasured heritage immortalized by the revolutionary Bhagat Singh and his comrades who were themselves inspired by the rebels of the Ghadar Party and young patriots like Khudiram Bose. It is the students who are the real patriots, the true `nationalists’.
* * *
Achieving universal access to education is not just a question of reaching a numerical target. It cannot be divorced from its democratic content and purpose. However, Indian capital, aligned with sections of the feudal landowning elite and accommodated with Brahmanical ideology which sanctions harshly exploitative caste divisions among the toiling masses, has brought both classes economic and political gain but only at the expense of the ruin of the majority of peasants, artisans, tribals, and working people. Having failed to break out of the vicious cycle of inequality the goal of universalizing school education could not be achieved. The education system inevitably sank into deep crisis which was aggravated each time a policy decision further narrowed access with multi-track discriminatory arrangements (alternate schools, multi-grade teaching, education guarantee centres, use of contractual and para-teachers, the RTE Act 2009).
The present regime’s proposed National Policy of Education 2016 (NEP 2016), which is now to be presented in its third avatar, promises to accelerate this process. Amendments to the already flawed RTE 2009 will allow for `alternate’ schools which do not `require’ the basic infrastructural and pedagogical norms laid down in the Act; will scrap the no-detention policy and vocationalize the elementary curriculum in targeted areas. Dove-tailed into the Skill Development program and the amended child labour law which now permits under14 year-olds to work in `family enterprises’, this `education’ policy will reinforce caste distinctions and ensure that the majority of India’s children from oppressed and marginalized sections will be condemned to a childhood of labour.
At the other end of the scale, centralization in the form of a single entrance exam for all government jobs at state level and for entry to professional institutions of higher education at an all-India level, have proved to be huge avenues for corruption.The CBI still has not found the time for properly investigating Madhya Pradesh’s `Vyapam’ scam even though the deaths of 49 persons, reaching up to the highest level of those in power, are directly associated with it. The National Eligibility-cum-Entrance Test (NEET) examination for entrance to professional higher education has already created a scandal involving leakage of question papers by the use of `share-in software’. Although six centres located at Delhi, Noida, Chandigarh, Lucknow, Bhuvaneshwar and Ranchi had been identified where candidates had used fraudulent means, the Delhi Police has been able to investigate only two in the past six months. Apart from this, centralisation has also facilitated the imposition of linguistic, regional and gender inequalities and other forms of social and personal oppression for examinees.
However, what is most alarming about these tests is that they `standardize’ merit according to the knowledge skills of the pampered elite section and jeopardize the interests of students from deprived sections. For this very reason standardization is a necessary demand of both the national and foreign investors whom the GOI is wooing to enter the higher education `market’ that is being secured for them. GOI and state governments are withdrawing from investing public funds in education which alone can ensure access to all, and defend and extend social justice measures like reservation of seats for scheduled castes, tribes, OBC’s, minorities, girls, transgenders and the disabled, and provide for adequate scholarships, hostels etc., for students from the deprived sections.
At the same time the central government has taken no steps whatsoever to withdraw the offer made to WTO-GATS accepting the imposition of international trade rules for services to be imposed on the higher education sector. This would leave students and teachers at the mercy of profiteering multi-national `edu-corporations’, a process which has led to massive student debt crises even in developed countries like the U.K. and U.S.A. Further, the uncritical welcome prepared for FDI and private corporate investment in higher education without retaining the regulatory control of Parliament, state Assemblies and statutory bodies, allows anti-democratic norms and procedures to be imposed in educational institutions. This also threatens national sovereignty.
The rising tide of protest actions, particularly in colleges and universities across the country, from FTII, IIT-M, CUH, JNU, DU, Jadavpur, Allahabad, Punjabi University , Rajasthan and BHU has seen a new trend of joint actions involving radical Ambedkarites and Marxists to socialists and Gandhians uniting against the ABVP, student wing of the RSS, whose members are increasingly functioning as police informers and agent provocateurs to disrupt student unity and derail protest movements by raising the bogey of `anti-national’ forces.
The increase in Hindutva vigilante mobs inflicting atrocities on Dalits and lynching Muslims in the name of `gauraksha’ has generated revulsion among democratic sections and intensified the protests. Dadri (where Mohd Akhlaq was lynched), Una (where Dalit youths were flogged leading to massive protests), Sharanpur (site of a Thakur attack on Dalits where the Bhim Army emerged like a Phoenix), the `disappearance’ of JNU student Najeeb Ahmed, the public murder of 16 year old Junaid Khan on a train from Delhi (which led to thousands across several cities coming out in a spontaneous `Not in My Name’ protest campaign). Their resistance also reflected anger at the fact that in every case the administration was ineffective if not complicit, that police didn’t build credible cases against the culprits, and the ruling SanghParivar/BJP either remained silent, or vindicated these criminal actions and even `honoured’ the perpetrators.
However, it is necessary to understand that there are also serious economic interests behind the political backing that is so cynically being provided to these lynch mobs. The restrictions sought to be imposed by the central government on the sale of cattle for slaughter is a severe attack on the economic interests and livelihood of dairy and other farmers and the tanning and leather industry. Framers will not be free to sell their cattle even when it becomes uneconomical to maintain them. These restrictions have already severely depressed the sale price of ageing oxen and cattle. If enforced as law, the ban will devastate the rural economy and throw large sections of the population into joblessness and an uncertain future.
The truth is that the Central government has allowed 100% FDI in March 2017 through automated route in e-commerce for food production and food-processing, to encourage easy access of foreign corporates in agri- and horticultural production, in dairy farming, the meat export sector, and in the tanning and leather manufacturing activity in India. A delegation headed by a special secretary of Ministry of Food Processing Industries has already invited agri- and food corporates of the USA to participate in a World Food Forum to be held in November 2017 in India. In fact, the much advertised ‘Make in India’ and ‘Digital India’campaigns are aimed at ruining Indian farmers, cattle breeders, producers and retailers of milk, meat and leather goods in order to “open up” a market for multi-national corporate giants. 
The RSS-BJP claim that the move is intended to protect indigenous cow breeds is a fraud. This is used only to conceal their true aim by taking cover under Directive Principle (article 48) of the Constitution which recommends, but does not make justiciable, “organizing agriculture and animal husbandry on modern and scientific lines and shall in particular take steps for preserving and improving breeds and prohibiting the slaughter of cows and calves and other milch and draft cattle.”
Constitutionally, however, agriculture and preservation of stock come under the exclusive purview of the state legislatures. Therefore, the Central government had to take recourse to the Prevention of Cruelty to Animals Act (1960) because rules for this Act can be framed by an executive order. But this Act in no way prevents slaughter of any animal for food purposes. Still less does it ban “sale for the purpose of slaughter” of selected animals. Therefore the Central government’s rules violate the 1960 Act, and more dangerously, constitute a threat to the federal structure of the Constitution itself.
Of course the fascist politics of the ban on cattle slaughter lies in the hindutva ideology of Hindu supremacy and the majoritarian character of the concept of `Hindu Rashtra’. This is a complete denial of the democratic pluralism of India’s republican Constitution. The Constitution makes no mention of religious sentiments either in Article 48 or in the 1960 Act. Still less does it seek to impose dietary preferences of a section of the population on other communities or individuals.
The so-called “beef ban” is nothing but an outright attack on the individual and socio-cultural right of the people to eat the food of their choice, and is a direct assault on the constitutional principles of secularism and federalism in India. 
At the end of three years of the Modi government, when economic growth figures have slumped to 6%, when jobs for the youth are nowhere to be found, when the foolhardy demonetization has dealt a severe blow to the informal sector which provides employment to over 80% of the working population, the incompetent Central government is scornfully and irresponsibly utilizing religious prejudice to polarize the people for its petty political gains.
In this polarized environment, the multi-pronged neoliberal and communal-fascist assault on the education system as a whole has grown more swift and reckless.
Government schools, colleges and universities are being starved of funds. GOI has systematically reduced its spending on education as percentage of GDP from an already inadequate 0.69% in FY2012, to 0.66% in FY 2013 and 0.63% in FY2014. A sharp drop to 0.55% in FY2015 dropped further to 0.49% in FY2016. The revised estimate for FY2017 was 0.48% while the budget estimate for FY2018 continues the trend at 0.47%. (CMIE & Mint calculations). This is despite the fact that an Educational Cess of 3 percent is imposed on everything, even a match-box, purchased by every Indian citizen. The claim that the contributions of state governments in a true spirit of federalism are taking up the financial responsibility for education, may prove to be just another `jumla’ of the Modi government. In a shocking step, the present Uttar Pradesh state government has cut budgetary funds for schools and colleges by 90% in this year’s budget! The secondary education allocation is down to Rs.576 crores from the previous government’s 2016-17 allocation of Rs.9,990 crores and the higher education allocation is down to Rs.272.77 crore from the previous government’s allocation of Rs.2,742 crores. 
Achieving universal access to education is not just a question of reaching numerical targets. It cannot be divorced from its democratic content and purpose. However, Indian capital, aligned with sections of the feudal landowning elite and accommodating with Brahmanical ideology which sanctions harshly exploitative caste divisions among the toiling masses, has allowed the ruling classes to gain economically and politically at the expense of the ruin of the majority of peasants, artisans, tribals, and working people. Having failed to break out of the vicious cycle of inequality the goal of universalizing school education could never be achieved. The education system inevitably sank into deep crisis which was aggravated each time a policy decision further narrowed access with multi-track discriminatory arrangements (alternate schools, multi-grade teaching, education guarantee centres, use of contractual and para-teachers, the RTE Act 2009).
Extreme shortage of teachers and infrastructure is forcing students to `desert’ the cash-starved government schools, and lured with the promise of a better future by studying in English medium private schools, even parents from the economically deprived sections are being driven to low-budget fee-paying schools catering to the weaker sections. In pursuit of the bankrupt Public Private Partnership (PPP) policy, central and state governments, re-imburse private schools for admitting at least 25% EWS students. In fact, this policy is not achieving the provision of better education to the EWS students; it is effectively pushing students towards the private schools market while transferring hundreds of crores of rupees worth of public funds into private hands. That is why central and state governments alike complain of a shortage of funds when they are required to invest in government schools. As a result government schools are rapidly deteriorating. Instead of correcting the decline, the so-called `rationalization’ policy of merger/closure has been adopted to divert remaining funds, teachers and students from such `non-performing’ schools. The policy has already led to closure of more than one and a half lakh schools across the country which is an irreparableloss to lakhs of poor students.
The decision to withdraw the no-detention policy, which at least kept children in school till the age of 14 years; the proposed introduction of skill development centres for elementary school children in tribal areas and inclusion of 25% `skilling’ courses in the school syllabus in tribal and backward regions; and legally permitting ten-year-old’s from economically weaker sections to work upto three hours per day in hereditary/family enterprises are all aimed at further contracting the government school system. Linking the mid-day meal scheme and scholarships for EWS and minority students with mandatory possession of Aadhar cards is a source of greater harassment which intends to further reduce the reach of the system. The result is a denial of the fundamental right to education for approximately 85% children in the relevant age group whose parents depend on public-funded schools for educating their children.
A similar strategy of fostering exclusion is being adopted in higher education. Severe cuts in public funding for colleges and universities have been combined with a decrease in student intake so that even central universities like JNU and Delhi University have had to cutback admissions by almost one-third. Some centres and departments have zero admissions quota this year. The reason is supposedly the UGC stipulation limiting the number of post-graduate/research students per faculty member. Then why not stagger the adjustment to the rule and increase the number of faculty? At any rate, India has one of the world’s lowest percentages of research scholars to total population.
The withdrawal of state funds has a direct impact on research scholarships. The `Occupy UGC’ movement supported by university students and teachers across the country focused on the failure to increase the amount of Junior and Senior Research Fellowships and instead to link them with clearing the NET exam which is an eligibility requirement for teaching jobs. The already overburdened CBSE has now been given the task of conducting the NET exam which it claims can only hold once in a year. The percentage of those who would clear it at any one sitting has been reduced to 6% from the present 16%. The intention is clear – slash research fellowships.
The greatest blow is thus dealt against students from disadvantaged sections and from backward regions who cannot pursue higher education without this support. The criteria for admission have also been changed to their disadvantage at premier institutions like JNU which had earlier made provision for students from such backgrounds. Deprivation points, measuring obstacles overcome by a candidate because of coming from an economically deprived or educationally backward region or community, will now only determine eligibility. Admission itself will be 100% determined by the interview. At this stage all the upper class, upper caste, and English-speaking elite sense of entitlement will aid their admission at the expense of the non-privileged candidates.
Given the extent and the threat of more fund cuts, colleges and university departments are either encouraged or forced to resort to starting self-financing courses or collaborate with corporates for projects to raise funds. While we fight fund cuts and commodification of education head on with the Government, corporates are rapidly gaining credibility and access to educational institutions through the back door. This must be exposed and resisted if the academic and institutional autonomy of the academic community is to be protected.
With this massive all-round assault on education, on the future of India’s youth and its democratic institutions, the importance of an all-India alliance of students in struggle was advanced by students themselves. The demand for coming together on a common platform, to be provided by the All India Forum for the Right to Education, evolved into the All India Convention of Students Struggles hosted on August 5th and 6th 2017 at Bengaluru. Delegates drawn from several progressive national student organizations, from organizations that are active at state or at institutional levels, and from among activists drawn from the upsurge of movements across the country gathered at Bengaluru’s Shikshakara Sadana, Kempegowda Road. Several teachers associations, academicians and public intellectuals who significantly influence the direction and success of student struggles by standing in solidarity with them were also present as observers.
The purpose of the Convention is to represent the spirit of resistance evident among the youth by evolving a collective understanding for charting future programmes of joint actions to challenge the policies of the GOI, the hindutva forces of the Sangh Parivar, and international forces pushing India towards a globalization and marketization of education – all of which are against the interests of the people and specially of the youth - through a genuinely widespread and united struggle in defence of education, democracy and peoples’ sovereignty.


