= The Students' Outpost - About
:published_at: 2017-07-11
:hp-tags: Students, Outpost, Union
:hp-alt-title: the students outpost about2

TSO is a group of young people who believe that students should be at the forefront of the emerging nation-wide resistance to Brahminism and fascism. Campuses across the country are in ferment, and it is vital that students politicize and organize to speak truth to power and resist the systematic saffronisation of higher education. We aim to be an open platform that will welcome thinkers, fighters and dreamers of all kinds, as we forge new solidarities and engage critically with questions of our day. The organization shall strive to unite students from across Bangalore in a collective effort that can channel our energies into political action, and in Ambedkar’s words, Educate, Agitate and Organize. Eschewing traditional forms of political organizing, we are in favour of an open, democratic space with no hierarchy (strongly in favour) or institutional affiliation. Only continual self-reflection; about our positions and our privileges will give us the tools to resist the profoundly unjust system we are complicit in.
TSO is born out of the hope that this an ideal that inspires more young people, and that when we come together, it can be the beginning of something truly radical, subversive and fearless.